---
abstract: "Modified debug behavior to create multi-line output that's easier for mere mortals to parse."
author:
  - 'Steve Dondley <s@dondley.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-DebugDump
resources:
  bugtracker: http://github.com/sdondley/Dancer2-Plugin-DebugDump/issues
  repository: git://github.com/sdondley/Dancer2-Plugin-DebugDump.git
version: '0.33'
x_serialization_backend: 'YAML::Tiny version 1.70'
