---
abstract: '[Run debug through Dumper for easier reading]'
author:
  - 'Steve Dondley <steve@debian.dondley.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-DebugDump
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.1'
x_serialization_backend: 'CPAN::Meta::YAML version 0.011'
